package jetbrains.mps.samples.StateChart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ChartOperation_Constraints extends BaseConstraintsDescriptor {
  public ChartOperation_Constraints() {
    super(MetaAdapterFactory.getConcept(0xc3b0572e7f864ac7L, 0xac44ef15dc8f5c15L, 0x5e8f0d038ab26a37L, "jetbrains.mps.samples.StateChart.structure.ChartOperation"));
  }

  public SAbstractConcept getDefaultConcreteConcept() {
    return MetaAdapterFactory.getConcept(0xc3b0572e7f864ac7L, 0xac44ef15dc8f5c15L, 0x5e8f0d038ab26aecL, "jetbrains.mps.samples.StateChart.structure.EmptyOperation");
  }
}
