package jetbrains.mps.lang.editor.init.test;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.testbench.util.CachingAppender;
import org.apache.log4j.Priority;

@MPSLaunch
public class ChildWithDirectCycle_card1n_Test extends BaseTransformationTest {
  @Test
  public void test_ChildWithDirectCycle_card1n() throws Throwable {
    initTest("${mps_home}", "r:5bc8da8a-ff96-4203-940f-04ea622e05a9(jetbrains.mps.lang.editor.init.test)");
    runTest("jetbrains.mps.lang.editor.init.test.ChildWithDirectCycle_card1n_Test$TestBody", "testMethod", false);
  }

  @MPSLaunch
  public static class TestBody extends BaseEditorTestBody {
    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("8705753908477435261", "8705753908477435267");
      typeString("card1n_direct_");
      invokeAction("jetbrains.mps.ide.editor.actions.Complete_Action");
    }
    @Override
    protected void populateExpectedEvents(CachingAppender appender) {
      appender.expectEvent(Priority.ERROR_INT, null);
    }
  }
}
