package jetbrains.mps.console.actions.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class TextPreviewGroup_Console_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "jetbrains.mps.console.actions.plugin.TextPreviewGroup_Console_ActionGroup";
  public TextPreviewGroup_Console_ActionGroup() {
    super("TextPreviewGroup_Console", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    TextPreviewGroup_Console_ActionGroup.this.addAction("jetbrains.mps.console.actions.plugin.ShowGenerationPlan_Action");
  }
}
