package jetbrains.mps.ide.java.newparser;

/*Generated by MPS */

import org.jetbrains.mps.openapi.module.ModelAccess;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.messages.IMessageHandler;
import com.intellij.openapi.application.ApplicationManager;

/*package*/ class IncrementalModelAccessWithCommand extends IncrementalModelAccessBase {
  public IncrementalModelAccessWithCommand(ModelAccess modelAccess, Iterable<SModel> models, IMessageHandler messageHandler) {
    super(modelAccess, models, messageHandler);
  }

  @Override
  public void replaceNodes(final Runnable runnable) {
    ApplicationManager.getApplication().invokeAndWait(new Runnable() {
      public void run() {
        myModelAccess.executeUndoTransparentCommand(runnable);
      }
    });
  }
}
