package jetbrains.mps.execution.configurations.pluginSolution.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.relations.BaseOrder;
import java.util.Arrays;

public class Executor_Order extends BaseOrder {
  public Executor_Order() {
    super(Arrays.asList(new String[]{"Run Configuration", "Executor"}));
  }
}
